#!/usr/bin/env bash

set -e

pushd ../svd
if [ ! -f stm32f7x7.svd ]; then
    #unzip -ojLL vendor/en.stm32f7_svd.zip
    cp ../stm32f7/stm32f7x7.svd .
fi

for f in ./*.svd*; do
    if [[ "$f" != *"stm32f7x7"* ]]; then
        rm -f "$f"
    fi
done
popd

pushd ../
make
popd
